### ISSUE TITLE
"get_data_then_refresh_screen" execution causes perpetual hang

### ISSUE THREAD

**Issue by AStoker** [trip5/ESPHome-eInk-Boards#4]
I ran into an interesting situation where my last update of the evening (9:05 PM) would frequently wake up my esphome and not put it back to sleep, eventually causing the battery to drain. I even tried to leave it plugged in to see if something funky was happening, but didn't see anything in the logs... Until I started poking around and adding some logger statements.
I ultimately traced the source of the issue down to this `if` statement, https://github.com/trip5/ESPHome-eInk-Boards/blob/9acf39264c27fa59acd6b57d2ae502ac3d5debdd/ESPHome_eink-weatherboard.yaml#L172

```yaml
- if:  # with longer sleep delays, the ESP32 tends to wake up a bit too early... if the wake time is within the next 8 minutes, wait for the scheduled wake time (less 30s) (preventing it from updating twice in a row)
    condition:
      lambda: 'return (id(wake_time_helper).state <= (8 * 60));'
    then:
      - delay: !lambda 'return (((id(wake_time_helper).state) - 30) * 1000);'
```

The issue is that the `wake_time_helper` could have a value less than 480 seconds (8 * 60). In particular, it could have a value less than 30 seconds (and in my case, the state was exactly 0 seconds). This can result in the delay method to be called with a negative value, ultimately making the execution hang indefinitely.

I'm currently playing around with adding a number helper to properly calculate the delay, simply checking if the subtraction of 30 results in a negative number, and if so, set to zero. We'll see if that helps, but wanted to document an issue here.
Thanks for your work on this, it was a huge help in getting me something up and running!

**Comment by trip5** [comment]
Wow.  Good catch.  If you find a solution, would you mind sharing it?

I'm currently away from my boards in another country but I had wondered why one of my boards was powered-on for a week before I left - and drained the battery... and I couldn't figure out why.  I think you're right that the `- 30` might be the culprit!

**Comment by AStoker** [comment]
Sure!
I'm literally just getting into esphome and yaml, so there might be a much better way to do this.

But what I'm doing is having a `number` to save my delay time (really it's just used so I can calculate it once and use it in some logging statements, besides that it really could just be calculated once at the delay time function):

```yaml
number:
  - platform: template
    name: "Delay Time Helper"
    id: delay_time_helper
    internal: true
    step: 1
    min_value: 0
    max_value: 9999999 # This should only be used to calculate how for to delay, shouldn't be more than a few minutes
    optimistic: True
```

Then I just modified the script's `get_data_then_refresh_screen` if statement to calculate the proper delay time, log it, and then wait:

```yaml
      - if:  # with longer sleep delays, the ESP32 tends to wake up a bit too early... if the wake time is within the next 8 minutes, wait for the scheduled wake time (less 30s) (preventing it from updating twice in a row)
          condition:
            lambda: 'return (id(wake_time_helper).state <= (8 * 60));'
          then:
            - lambda: |
                int delay_time = (id(wake_time_helper).state - 30) < 0 ? 0 : (id(wake_time_helper).state - 30);
                id(delay_time_helper).publish_state(delay_time);  // Store value for use in logger.log
            - logger.log:
                format: "Woke up too soon (within 8 minutes). Wake Time Helper is set to %.1f seconds. Waiting for %.1f seconds before refreshing display."
                args: ['id(wake_time_helper).state', 'id(delay_time_helper).state']
            - delay: !lambda 'return (id(delay_time_helper).state * 1000);'
```

I'll give it a few days to try and reproduce the issue. If it seems to work fine, I can make a PR for you.
